### ISSUE TITLE
Premenovanie teamu a repozitaru

### ISSUE THREAD

**Issue by fr6nco** [aks-2017/semestralne-zadania-semestralne-zadanie-xsosnak-xmoravcikm4#1]
Ahojte,

zle som sa vyjadril v maili. Proism poslite mi vase x[meno] loginy ja updatenem meno timu a repozitaru. Budete musiet asi updatenut origin vo vasich gitoch.

Tomas

**Comment by jacky035** [comment]
Dobrý deň,

naše loginy sú xsosnak (Matúš Sosňak) a xmoravcikm4 (Marko Moravčík)

S pozdravom

Matúš Sosňak

Dňa 23. októbra 2017, 10:49, Thomas Boros <notifications@github.com>
napísal(-a):

**Comment by jacky035** [comment]
xsosnak  xmoravcikm4
